image: openjdk:8

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw clean package
  artifacts:
    paths:
      - target/conf-automation-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=conf-automation --api-key=$HEROKU_API_KEY
  only:
    - master
