application:
  speaker: Nicolas Fränkel
  name: Conference workflow automation
  feishu:
    max-row: 199
spring:
  application.name: ${application.name}
  datasource.driver-class-name: org.postgresql.Driver
logging.level.reactor.netty.http.client: DEBUG
