application:
  trello:
    ips:
      - 107.23.104.115
      - 107.23.149.70
      - 54.152.166.250
      - 54.164.77.56
      - 54.209.149.230
      - 18.234.32.224/28
spring:
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
server:
  forward-headers-strategy: framework