application:
  speaker: Nicolas Fränkel
  name: Conference workflow automation
  version: '@project.version@'
spring:
  application.name: ${application.name}
  datasource.driver-class-name: org.postgresql.Driver
camunda.bpm.history-level: none
